title: Muru not so great
author: Muru
email: muruvetri@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog post is mistakes at work and understanding them and hopes nobody catches them
# social links
twitter_username: muru1 # DO NOT include the @ character, or else the build will fail!
github_username:  muruvetri # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
